import { Link } from 'react-router-dom';
import { ArrowRight, Sparkles, Layers, Wand2, Play } from 'lucide-react';
import { motion } from 'motion/react';

export function Home() {
  const galleryImages = [
    { url: "https://picsum.photos/seed/miami_living/800/1000", title: "Living Room", style: "Luxury Modern" },
    { url: "https://picsum.photos/seed/marble_bath/800/1000", title: "Master Bath", style: "Minimalist" },
    { url: "https://picsum.photos/seed/art_deco_bedroom/800/1000", title: "Bedroom", style: "Art Deco" },
    { url: "https://picsum.photos/seed/coastal_kitchen/800/1000", title: "Kitchen", style: "Coastal Chic" },
  ];

  return (
    <div className="min-h-screen bg-background text-primary overflow-hidden">
      {/* Hero Section */}
      <section className="relative min-h-[90vh] flex items-center justify-center px-6 pt-20 pb-32">
        <div className="absolute inset-0 z-0 opacity-40">
          <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-accent/20 rounded-full blur-[120px]" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[60%] h-[60%] bg-primary/5 rounded-full blur-[150px]" />
        </div>
        
        <div className="relative z-10 max-w-5xl mx-auto text-center">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-border bg-white/50 backdrop-blur-md mb-8"
          >
            <Sparkles className="w-4 h-4 text-accent" />
            <span className="text-xs uppercase tracking-widest font-medium">Miami Luxury Design Assistant</span>
          </motion.div>
          
          <motion.h1 
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.2, ease: "easeOut" }}
            className="text-5xl md:text-7xl lg:text-8xl font-serif font-light leading-[1.1] tracking-tight mb-8"
          >
            Elevate your <br className="hidden md:block" />
            <span className="italic text-muted-foreground">interior vision.</span>
          </motion.h1>
          
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4, ease: "easeOut" }}
            className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-12 font-light leading-relaxed"
          >
            The digital extension of a luxury interior designer. Generate, edit, and refine high-end spaces with precision AI tools curated by Paula Ambrosio.
          </motion.p>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6, ease: "easeOut" }}
            className="flex flex-col sm:flex-row items-center justify-center gap-6"
          >
            <Link 
              to="/dashboard" 
              className="group relative px-8 py-4 bg-primary text-primary-foreground rounded-full overflow-hidden transition-all hover:scale-105"
            >
              <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-500 ease-out" />
              <span className="relative flex items-center gap-2 text-sm uppercase tracking-widest font-medium">
                Login / Sign Up <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </span>
            </Link>
            <Link 
              to="/dashboard?demo=true" 
              className="flex items-center gap-2 px-8 py-4 bg-transparent text-primary border border-primary/20 rounded-full hover:bg-primary/5 transition-colors text-sm uppercase tracking-widest font-medium"
            >
              <Play className="w-4 h-4" /> View Demo
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Gallery Section */}
      <section className="py-24 bg-muted/30 border-y border-border/50">
        <div className="max-w-[1400px] mx-auto px-6">
          <div className="flex flex-col md:flex-row justify-between items-end mb-16 gap-6">
            <div>
              <h2 className="text-3xl md:text-5xl font-serif font-light mb-4">Created with Studio</h2>
              <p className="text-muted-foreground uppercase tracking-widest text-sm">Inspiring spaces generated by our AI</p>
            </div>
            <Link to="/dashboard?demo=true" className="text-xs uppercase tracking-widest font-medium hover:text-accent transition-colors flex items-center gap-2">
              Try it yourself <ArrowRight className="w-3 h-3" />
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {galleryImages.map((img, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: i * 0.1 }}
                className="group relative aspect-[3/4] rounded-2xl overflow-hidden bg-muted"
              >
                <img 
                  src={img.url} 
                  alt={img.title}
                  className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 flex flex-col justify-end p-6">
                  <p className="text-white/70 text-[10px] uppercase tracking-widest mb-1">{img.style}</p>
                  <h3 className="text-white font-serif text-xl">{img.title}</h3>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-32 bg-white relative">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-20">
            <h2 className="text-3xl md:text-5xl font-serif font-light mb-6">Curated Intelligence</h2>
            <p className="text-muted-foreground uppercase tracking-widest text-sm">Not a tool. A premium creative weapon.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-12">
            {[
              {
                icon: <Wand2 className="w-8 h-8 stroke-[1.5]" />,
                title: "Nano Banana PRO 2",
                desc: "Industry-leading generation model tailored for hyper-realistic luxury interiors, lighting, and textures."
              },
              {
                icon: <Layers className="w-8 h-8 stroke-[1.5]" />,
                title: "Precision Editing",
                desc: "Smart masking, object replacement, and fine-tuning. Adjust materials and composition with architectural accuracy."
              },
              {
                icon: <Sparkles className="w-8 h-8 stroke-[1.5]" />,
                title: "Design Assistant",
                desc: "Context-aware suggestions based on high-end Miami design trends, ensuring aesthetic balance in every render."
              }
            ].map((feature, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.8, delay: i * 0.2 }}
                className="p-8 rounded-3xl bg-background border border-border/50 hover:shadow-xl hover:-translate-y-2 transition-all duration-500"
              >
                <div className="w-16 h-16 rounded-2xl bg-primary/5 flex items-center justify-center text-primary mb-8">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-serif mb-4">{feature.title}</h3>
                <p className="text-muted-foreground leading-relaxed font-light">{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
